name: Run Updater - Update Korea subway stations data
on:
  schedule:
    - cron:  '0 */12 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.15
      uses: actions/setup-python@v1
      with:
          python-version: '3.6.15'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run updater.py with python
      run: |
        python "updater.py"
