name: Run Updater - Update Korea subway stations data
on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.5
      uses: actions/setup-python@v1
      with:
          python-version: '3.6.5'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==1.4.0
    - name: Run updater.py with python
      run: |
        python "updater.py"
    - name: Commits
      run: |
        git config --local user.email "dartbird.yu@gmail.com"
        git config --local user.name "dart-bird(auto)"
        git add *.json
        git commit -m "Auto - Update Korea stations data"
    - name: Push
      uses: ad-m/github-push-action@main
      with:
        branch: 'main'
        github_token: $ 
